### ISSUE TITLE
issue I can't figure out

### ISSUE THREAD

**Issue by pjhalsli** [NelsonBrandao/absolute#1]
I see there's been some time since you've been active here but I'll try anyway;
I get this in my terminal
_prompt_nvm:1: command not found: nvm
and have no ideo how to fix it. I'm on Arch Linux and nvm is installed.
Any help would be highly appreciated.

**Comment by NelsonBrandao** [comment]
Hi, did you follow the zsh setup on nvm [GitHub page](https://github.com/nvm-sh/nvm#zsh)?

**Comment by pjhalsli** [comment]
No - I'm not a programmer and don't use nvm  I just liked your zsh theme - but as I got that error I installed nvm 'cause I thought that would fix it - but it didn't.

I'll take a look at the link you posted - thanks
